# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bca9eb0a9b068140c55f841366602e61a8188943bc68976c237a81fff182d2f30d54cda8e093e02b450d19540aeadfab9b45f14066b8b29a301abbe3f490691c

test:
  secret_key_base: 6f8ab86c07ac5e3e677e4f43e9fdedf46155b7abf20252f8d694f97b7641e7a225ab4068d8923febe81804421d8f622265d15e0b2cde8f5cf617d890abda6bc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
